In [3]:
import numpy as np
from scipy.optimize import linprog


costs = np.array([[3, 12, 9, 1, 7],
                  [2, 4, 11, 2, 10],
                  [7, 14, 12, 5, 8]])


supply = np.array([350, 330, 270])
demand = np.array([210, 170, 220, 150, 200])

c = costs.flatten()

A_eq = np.zeros((len(supply) + len(demand), len(c)))
b_eq = np.zeros(len(supply) + len(demand))

for i in range(len(supply)):
    A_eq[i, i * len(demand):(i + 1) * len(demand)] = 1
    b_eq[i] = supply[i]


for j in range(len(demand)):
    A_eq[len(supply) + j, j:len(c):len(demand)] = 1
    b_eq[len(supply) + j] = demand[j]

result = linprog(c, A_eq=A_eq, b_eq=b_eq, method='highs')
solution = result.x.reshape(costs.shape)


print("Оптимальний план:")
print(solution)
print("\nTotal Cost:", result.fun)

Оптимальний план:
[[ 50.   0. 150. 150.   0.]
 [160. 170.   0.   0.   0.]
 [  0.   0.  70.   0. 200.]]

Total Cost: 5090.0
